### ISSUE TITLE
Web Introduction Task

### ISSUE THREAD

**Issue by lespavl** [lespavl/beetroot-academy#1]
Установить:
* Браузеры:
    * Chrome https://www.google.ru/chrome/browser/desktop/
    * Mozilla Firefox https://www.mozilla.org/ru/firefox/new/
    * Opera http://www.opera.com/ru
    * Safari http://safari.ru.softonic.com/
    * IE http://windows.microsoft.com/uk-ua/internet-explorer/download-ie 
* Sublime Text 3 - http://www.sublimetext.com/3 
* создать аккаунт на Google и Google Drive - https://www.google.com/intl/ru_ua/drive/ 
* Filezilla http://filezilla.ru/get/ 
* Git - https://git-scm.com/ 
* Lightshot https://app.prntscr.com 
* Создать аккаунт на Github и написать комментарий к этому заданию.

**Comment by monakhovm** [comment]
1st comment

**Comment by ValentinIl** [comment]
2nd comment. Good luck

**Comment by mrKru** [comment]
Hi! Peace for everyone!))

**Comment by 3109** [comment]
Hi! One point done!

**Comment by EvgeniiaMoi** [comment]
Hi! Good luck everybody:)

**Comment by olgaste** [comment]
Ok, it's done! Приветствую ;)

**Comment by BazhenovD** [comment]
Comment)

**Comment by pro100264** [comment]
done

**Comment by KateMore** [comment]
Hi! From Katya with love!

**Comment by lespavl** [comment]
Не хватает одного последнего комментария :)

**Comment by zlodeh** [comment]
I'm hera. Hakop

**Comment by lespavl** [comment]
Тогда еще одного последнего комментария))

**Comment by Meolie** [comment]
+

**Comment by lespavl** [comment]
Ура, мы наконец-то все сделали первое домашнее задание :)
