### ISSUE TITLE
lesson 1 - HTML Introduction Task

### ISSUE THREAD

**Issue by lespavl** [lespavl/beetroot-academy#2]
* Зарегистрироваться на http://htmlacademy.ru
* Пройти курсы:
    * Структура HTML-документа
    * Разметка текста с помощью HTML
    * Ссылки и изображения
* Добавить комментарий к этому заданию со ссылкой на профиль HtmlAcademy
* Создать небольшое резюме, которое содержит фотографию и несколько ссылок на соц.сети, а также краткую информацию о себе. Загрузить резюме на Google Drive и прислать ссылку в комментарии сюда.

**Comment by EvgeniiaMoi** [comment]
Курсы:
https://htmlacademy.ru/profile/id118546
Небольшое резюме:
https://drive.google.com/drive/my-drive

**Comment by mrKru** [comment]
Профиль HtmlAcademy:
https://htmlacademy.ru/profile/id156617
Резюме:
https://drive.google.com/drive/my-drive

**Comment by lespavl** [comment]
Женя, Влад, молодцы) Самые быстрые)
Но у вас неправильные ссылки, не получается зайти и посмотреть.
Вот небольшая инструкция, как скопировать правильную ссылку:
Правый клик мышкой по папке, выбираем "Совместный доступ": http://prntscr.com/98iiiv
Дальше нажимаем "Включить доступ по ссылке": http://prntscr.com/98iis1
Копируем ссылку: http://prntscr.com/98iixk

**Comment by ValentinIl** [comment]
Профиль:
https://htmlacademy.ru/profile/id156628
Резюме:
https://drive.google.com/file/d/0B5tf9W48xWCQWFQtQU1RV19GRVU/view?usp=sharing

**Comment by mrKru** [comment]
https://drive.google.com/folder/d/0B-pEt4HvzDDoSFFmLWllUm5rTzg/edit

**Comment by KateMore** [comment]
Резюме: https://drive.google.com/folderview?id=0B0XGX9c2bRRKNnE4M296czQ2MTA&usp=sharing
Профиль: https://htmlacademy.ru/profile/id157110

**Comment by EvgeniiaMoi** [comment]
Леся, спасибо за детальную инструкцию:)
Вот, надеюсь, правильная ссылка:
https://drive.google.com/folderview?id=0Bz2nINgHzhH-X1BvbGJFSDlfSEE&usp=sharing

**Comment by olgaste** [comment]
Приветствую :)
https://htmlacademy.ru/profile/id156913
https://drive.google.com/folderview?id=0B5dLnsOb0Rk8aVZFUURFWFVicXM&usp=sharing

**Comment by 3109** [comment]
Resume: https://drive.google.com/file/d/0B9agK9b3AioYVTdfa1RfR1gzWEE/view?usp=sharing
Profile: https://github.com/3109

**Comment by pro100264** [comment]
Resume https://drive.google.com/file/d/0B6X2L_pGLeOgYXhGb3BlV2w1VzQ/view?usp=sharing
Profile https://htmlacademy.ru/profile/id157033

**Comment by zlodeh** [comment]
https://drive.google.com/folderview?id=0B8A4PaVZFWiZdEZDbTZZVWZMaXc&usp=sharing

https://htmlacademy.ru/profile/id107334

**Comment by Meolie** [comment]
https://drive.google.com/file/d/0B6eJLnhMnRKxZ1ZhRGxxenl1MWc/view
https://htmlacademy.ru/profile/id158242

**Comment by BazhenovD** [comment]
https://drive.google.com/folderview?id=0B44O2m8ktXX-TkEycXBUTnpRYlU&usp=sharing
Резюме
https://htmlacademy.ru/profile/id156573
профиль

**Comment by lespavl** [comment]
Максим
https://htmlacademy.ru/profile/id161864
https://drive.google.com/folderview?id=0B6VBEjbNXsf6cWJURlJVa0xPUWM&usp=sharing
