### ISSUE TITLE
Install web server

### ISSUE THREAD

**Issue by lespavl** [lespavl/beetroot-academy#26]
Сначала скачайте и установите этот пакет: https://www.microsoft.com/en-us/download/details.aspx?id=5582

Затем на сайте https://www.apachefriends.org/ru/index.html скачайте XAMPP для Windows. Далее установите пакет в такое место, чтоб полный путь к папке не содержал пробелов или русских символов. Например, `D:/xampp`. После установки запустите xampp-control.exe. Нажмите на кнопки Start для Apache и Mysql. Если не получилось и они не стали зелененькими, выключите скайп и антивирус и попробуйте еще раз. Если ошибок нет, откройте в браузере страницу `http://localhost/`

Если что, [здесь](https://masalkin.name/ustanovka-i-nastrojka-xampp-vmesto-denwer-a/) можно посмотреть наглядную инструкцию со скриншотами

**Comment by ValentinIl** [comment]
готово
